/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AuthContent: typeof import('./components/AuthContent.vue')['default']
    ChromeExtension: typeof import('./components/ChromeExtension.vue')['default']
    ComingSoon: typeof import('./components/comingSoon.vue')['default']
    DePoAP: typeof import('./components/DePoAP.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Particles: typeof import('./components/Particles.vue')['default']
    ProofOfLife: typeof import('./components/ProofOfLife.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
